name: Reproduction

on:
  pull_request:
    branches:
      - main

concurrency:
  group: code-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  reproduction:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: Reproduction
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.1.9"
          - "1.1.10"
          - "1.1.11"
          - "1.1.12"
          - latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.version }}
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Run Tests
        run: bun test
        env:
          KEYVAULT_URL: ${{ secrets.KEYVAULT_URL }}
